spring:
  application:
    name: algorithm_quiz_curator
  datasource:
    url: jdbc:mysql://db.park-yh.com:3306/aqc_dev?autoReconnect=true&useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://db.park-yh.com:3306/aqc?autoReconnect=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: aqc_dev
    password: yhcy!@#$
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

jwt:
  token:
    header: api_key
    issuer: algorithm_quiz_curator
    clientSecret: yhcycyyh
    expirySeconds: 3600

custom:
  pageable:
    offset: 0
    limit: 5

async:
  thread:
    threadNamePrefix: async-thread-
    corePoolSize: 10  # 동시에 실행시킬 쓰레드의 갯수
    maxPoolSize: 50   # 쓰레드 풀의 최대 사이즈
    queueCapacity: 100 # 쓰레드 풀 큐의 사이즈. corePoolSize 갯수를 넘어서는 task가 들어왔을 때 queue에 해당 task들이 쌓이게 됩니다. 최대로 maxPoolSize 갯수만큼 쌓일 수 있습니다.